2025-04-24 20:55:57,079 - WARNING - Output directory 'TNG300_ICS' does not exist: /caefs/data/IllustrisTNG/300/ICS
2025-04-24 20:55:57,081 - WARNING - Output directory 'TNG300_snapshot99' does not exist: /caefs/data/IllustrisTNG/snapshot-99-dm-npy/cache
2025-04-24 20:55:57,081 - WARNING - Output directory 'NPY' does not exist: /caefs/data/IllustrisTNG/300/ICS
2025-04-24 20:56:00,335 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/dataprep/input_z=0/01-2_compute_densitymap_missing.py", line 101, in <module>
    particles = load_particles(in_path, dataset_path)
  File "/caefs/user/mmingyeong/structura/Structura/src/example/dataprep/input_z=0/01-2_compute_densitymap_missing.py", line 40, in load_particles
    with h5py.File(file_path, 'r') as f:
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/h5py/_hl/files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)
