2025-04-16 16:18:01,136 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,197 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,196 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,196 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,295 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,305 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,338 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,486 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:01,518 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,228 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,262 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,283 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,284 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,316 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,322 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,337 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,346 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,464 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,464 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:35,481 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:39,282 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:49,124 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:49,241 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:49,376 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=1000000)
2025-04-16 16:18:49,863 - INFO - 후처리 정규화 적용: total_density 보정 (입자 수=680412)
2025-04-16 16:19:52,086 - ERROR - Unhandled exception occurred:
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/concurrent/futures/process.py", line 211, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/density_kde_seq_chunks/01_compute_densitymap_batch.py", line 177, in <module>
    cProfile.run('main()', filename='cprofile_batch_density.prof')
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 17, in run
    return _pyprofile._Utils(Profile).run(statement, filename, sort)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/profile.py", line 54, in run
    prof.run(statement)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 96, in run
    return self.runctx(cmd, dict, dict)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 101, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/caefs/user/mmingyeong/structura/Structura/src/example/density_kde_seq_chunks/01_compute_densitymap_batch.py", line 161, in main
    compute_density_map(
  File "/caefs/user/mmingyeong/structura/Structura/src/example/density_kde_seq_chunks/01_compute_densitymap_batch.py", line 120, in compute_density_map
    partial_maps = list(results)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
MemoryError
