2025-03-05 16:00:26,567 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/check_system_ex.py", line 16, in <module>
    from system_checker import SystemChecker, LAST_UPDATE_DATE  # ✅ 최신 업데이트 날짜 추가
  File "/caefs/user/mmingyeong/structura/Structura/src/system_checker.py", line 12, in <module>
    import cupy as cp
ModuleNotFoundError: No module named 'cupy'
