2025-03-08 13:25:23,547 - INFO - GPU is available. CuPy will be used for FFT.
2025-03-08 13:25:24,488 - INFO - Using GPU device 1.
2025-03-08 13:25:24,489 - INFO - Output directory 'TNG300_ICS' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-08 13:25:24,489 - INFO - Output directory 'TNG300_snapshot99' is set to: /caefs/data/IllustrisTNG/snapshot-99-dm-npy/cache
2025-03-08 13:25:24,489 - WARNING - Output directory 'NPZ' does not exist: /path/to/your/output/npz
2025-03-08 13:25:24,489 - INFO - Output directory 'NPY' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-08 13:25:24,489 - WARNING - Output directory 'LOGS' does not exist: /path/to/your/logs
2025-03-08 13:25:24,489 - INFO - Snapshot99 데이터 폴더: /caefs/data/IllustrisTNG/snapshot-99-dm-npy/cache
2025-03-08 13:25:24,490 - INFO - Output directory: /caefs/user/mmingyeong/structura/Structura/src/results
2025-03-08 13:25:24,490 - INFO - 전체 Snapshot99 데이터를 로드합니다...
2025-03-08 13:25:25,105 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 191, in <module>
    main()
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 180, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 20, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/profile.py", line 63, in runctx
    prof.runctx(statement, globals, locals)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/cProfile.py", line 101, in runctx
    exec(cmd, globals, locals)
  File "fft_kde_ex.py", line 96, in <module>
    main()
  File "fft_kde_ex.py", line 35, in main
    positions = loader.load_all_chunks(sampling_rate=1)
  File "/caefs/user/mmingyeong/structura/Structura/src/data_loader.py", line 162, in load_all_chunks
    chunk_dask = da.from_delayed(delayed_chunk, shape=(None, num_columns), dtype=data_dtype)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/dask/array/core.py", line 4031, in from_delayed
    return Array(graph, name, chunks, dtype=dtype, meta=meta)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/dask/array/core.py", line 1376, in __new__
    self._chunks = normalize_chunks(chunks, shape, dtype=dt)
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/dask/array/core.py", line 3244, in normalize_chunks
    if allints or isinstance(sum(sum(_) for _ in chunks), int):
  File "/home/users/mmingyeong/.conda/envs/new_env/lib/python3.10/site-packages/dask/array/core.py", line 3244, in <genexpr>
    if allints or isinstance(sum(sum(_) for _ in chunks), int):
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
