2025-03-05 16:15:53,164 - INFO - ✅ Using GPU device 1.
2025-03-05 16:15:53,165 - WARNING - ⚠️ Output directory 'NPZ' does not exist: /path/to/your/output/npz
2025-03-05 16:15:53,166 - INFO - 📁 Output directory 'NPY' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 16:15:53,166 - WARNING - ⚠️ Output directory 'LOGS' does not exist: /path/to/your/logs
2025-03-05 16:15:53,169 - INFO - 📁 Input (npy) folder: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 16:15:53,169 - INFO - 📁 Output folder: /caefs/user/mmingyeong/structura/Structura/src/results
2025-03-05 16:15:53,170 - INFO - 📂 Detected 313 .npy files in the input folder.
2025-03-05 16:15:53,170 - INFO - 📄 Example file: chunk_89.npy
2025-03-05 16:15:53,170 - INFO - ✅ X range set: 64358.89 - 71133.51 ckpc/h (Center: 100 cMpc/h, Thickness: 10 cMpc/h)
2025-03-05 16:15:53,171 - INFO - 🔹 Filtering X range: 64358.89 - 71133.51 ckpc/h (64.359 - 71.134 cMpc/h)
2025-03-05 16:15:53,171 - INFO - 🔹 Loading data...
2025-03-05 16:23:19,870 - INFO - ✅ Time taken to load all chunks: 446.70s
2025-03-05 16:23:19,871 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/visualization_ex.py", line 52, in <module>
    positions = loader.load_all_chunks(x_min=x_min, x_max=x_max, sampling_rate=1)
  File "/caefs/user/mmingyeong/structura/Structura/src/data_loader.py", line 152, in load_all_chunks
    return cp.vstack([cp.asarray(chunk) for chunk in filtered_chunks])
  File "/caefs/user/mmingyeong/structura/Structura/src/data_loader.py", line 152, in <listcomp>
    return cp.vstack([cp.asarray(chunk) for chunk in filtered_chunks])
  File "/home/users/mmingyeong/.conda/envs/mingyeong310/lib/python3.10/site-packages/cupy/_creation/from_data.py", line 88, in asarray
    return _core.array(a, dtype, False, order, blocking=blocking)
  File "cupy/_core/core.pyx", line 2455, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2482, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2635, in cupy._core.core._array_default
  File "cupy/cuda/pinned_memory.pyx", line 357, in cupy.cuda.pinned_memory.is_memory_pinned
  File "cupy_backends/cuda/api/runtime.pyx", line 717, in cupy_backends.cuda.api.runtime.pointerGetAttributes
  File "cupy_backends/cuda/api/runtime.pyx", line 146, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
