2025-03-05 18:09:53,723 - INFO - ✅ Using GPU device 1.
2025-03-05 18:09:53,725 - WARNING - ⚠️ Output directory 'NPZ' does not exist: /path/to/your/output/npz
2025-03-05 18:09:53,725 - INFO - 📁 Output directory 'NPY' is set to: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 18:09:53,725 - WARNING - ⚠️ Output directory 'LOGS' does not exist: /path/to/your/logs
2025-03-05 18:09:53,726 - INFO - 📁 Input (npy) folder: /caefs/data/IllustrisTNG/300/ICS
2025-03-05 18:09:53,726 - INFO - 📁 Output folder: /caefs/user/mmingyeong/structura/Structura/src/results
2025-03-05 18:09:53,727 - INFO - 📂 Detected 313 .npy files in the input folder.
2025-03-05 18:09:53,727 - INFO - 📄 Example file: chunk_89.npy
2025-03-05 18:09:53,727 - INFO - ✅ X range set: 64358.89 - 71133.51 ckpc/h (Center: 100 cMpc/h, Thickness: 10 cMpc/h)
2025-03-05 18:09:53,727 - INFO - 🔹 Filtering X range: 64358.89 - 71133.51 ckpc/h (64.359 - 71.134 cMpc/h)
2025-03-05 18:09:53,727 - INFO - 🔹 Loading data...
2025-03-05 18:10:44,469 - INFO - ✅ Time taken to load all chunks: 50.74s
2025-03-05 18:10:44,645 - INFO - ✅ Data loaded successfully. Shape: (5161333, 3)
2025-03-05 18:10:44,645 - INFO - 🔹 Generating 2D histogram, saving to ../results/...
2025-03-05 18:10:44,645 - ERROR - Unhandled exception occurred:
Traceback (most recent call last):
  File "/caefs/user/mmingyeong/structura/Structura/src/example/visualization_ex.py", line 61, in <module>
    viz.plot_2d_histogram(
TypeError: Visualizer.plot_2d_histogram() got an unexpected keyword argument 'x_range'
